### ISSUE TITLE
[SCB Connect] Jenkins Jobs[DEV/QA] can not open log.html of robot framework.

### ISSUE THREAD

**Issue by Folkuuu** [digitalventures/devops-issue#1]
ไม่สามารถเปิด log.html จากผลการรัน Automate ที่ Job ได้ตามภาพด้านล่าง
![image](https://user-images.githubusercontent.com/31461782/108824874-d6bb4800-75f4-11eb-8bf6-b9e5a3538eb9.png)

**Comment by JATUNON** [comment]
done.
